### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by noorbakerally** [timmartin19/mimetype-match#1]
Hello, nice tool, however when importing, i'm getting this error:
ImportError: No module named mimetype_match

& I do the module installed:

my list of python modules installed
['accept-types==0.3.0', 'decorator==4.0.9', 'flask==0.10.1', 'html5lib==1.0b8', 'isodate==0.5.4', 'itsdangerous==0.24', 'jinja2==2.8', 'keepalive==0.4.1', 'markupsafe==0.23', 'mimetype-match==1.0.1', 'pyparsing==1.5.7', 'rdfextras==0.4', 'rdflib-jsonld==0.3', 'rdflib==4.2.1', 'simplejson==3.8.0', 'sparqlwrapper==1.7.4', 'validators==0.10', 'werkzeug==0.10.4']

**Comment by timmartin19** [comment]
You should be able to import it via 

```
import accept_header_match
```

I changed the name and didn't properly update everything.  Feel free to submit a pull request.  Otherwise, I probably wont get around to updating it until next week.

**Comment by noorbakerally** [comment]
nopes it still doesn't work

**Comment by timmartin19** [comment]
Hm... The packaging appears to have been broken.   I'll try to get a fix out tonight.

**Comment by timmartin19** [comment]
I'm sorry I was slow on getting this out.  I've been traveling a bit.  But I fixed setuptools and you should be able to appropriately import it now.

```
import mimetype_match
```

**Comment by noorbakerally** [comment]
Great, thanks !!
